### ISSUE TITLE
Misparsing when number of entries in PDT and NDX files differ

### ISSUE THREAD

**Issue by Alexander-TX** [tataranovich/jtv2xmltv#5]
Example JTV file attached
[schedule1.jtv.zip](https://github.com/tataranovich/jtv2xmltv/files/6883099/schedule1.jtv.zip)

**Comment by tataranovich** [comment]
Original issue description from blog post: https://blog.tataranovich.com/2019/05/jtv2xmltv.html?showComment=1627269952390#c3473532218661866366

>По-моему, вы неправильно парсите JTV-программу.
>
>NDX-файл содержит смещения к строкам с названиями передач в PDT файле. Ваш парсер ожидает, что в NDX и PDT файлах одинаковое число записей — каждой паре дата/смещение в NDX соответствует ровно одна строка в PDT (см. 1). Но провайдер может уменьшить размер PDT-файла, объединив повторяющиеся строки в одну и поставив в соответствующие записи NDX смежение на неё. Совершенно логичная оптимизация, т.к. одни и те же программы часто повторяются по нескольку раз в неделю. У других парсеров при этом не возникнет проблем, а ваш подставит в XMLTV неправильное название передачи.
>
>[1] https://github.com/tataranovich/jtv2xmltv/blob/7989355a5b3ffa9198507281eaf58858877a1d18/jtv2xmltv/convert.py#L52
