### ISSUE TITLE
Multiple increase in output file size

### ISSUE THREAD

**Issue by Losenmann** [tataranovich/jtv2xmltv#6]
When transferring a certain JTV archive, the resulting output file exceeds 350 MByte. Also, apparently, the xml format breaks in part of the output file and the records in the file, apparently, begin to be duplicated. A cursory analysis showed that some pdt and ndx pairs cause problems. Removing these files solves the problem. It was not possible to find out why certain pairs (pdt and ndx) cause problems. pdt encoding is correct. The ndx file may contain control characters.
An example of a problematic file: https://disk.yandex.ru/d/J4ozlcXM89WUng

**Comment by tataranovich** [comment]
I checked 1115.ndx/1115.pdt files from the problematic JTV file. According to the [JTV format](https://github.com/tataranovich/jtv2xmltv/blob/master/docs/JTV.md) definition that I have, some of the references from 1115.ndx file have incorrect offset to 1115.pdt file.

Example is record 1361 in 1115.ndx file (offset 0x3fce):

```
0003fc0 ff9a 0000 4a00 9789 38ea 01d9 ffdc 0000
0003fd0 9200 44b0 38ec 01d9 0018 0000 6600 395e
```
12 bytes from the record (the last two are offset to PDT file in LE byte order): 00 00 00 92 B0 44 EC 38 D9 01 18 00

At 0x0018 offset in 1115.pdt file should be the length of title but it's pointing to the end of JTV header
```
00000000  4a 54 56 20 33 2e 78 20  54 56 20 50 72 6f 67 72  |JTV 3.x TV Progr|
00000010  61 6d 20 44 61 74 61 0a  0a 0a 23 00 c5 ed ee f2  |am Data...#.....|
```
As a workaround you can try to use jtv2xmltv 0.2.1 which is not strictly following JTV format and can help in this case.

**Comment by Losenmann** [comment]
Thank you, yes indeed there are no problems on version 0.2.1. It would be convenient if an additional cli key appeared, when enabled, the code block responsible for non-strict file processing was called. I'd rather see this feature in the next release.
